# Generated by Django 3.0.8 on 2022-03-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
